version: '3'
services:
  eureka-server-1:
    image: springcloud-example/eureka-server
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eureka-server-1
  eureka-server-2:
    image: springcloud-example/eureka-server
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=eureka-server-2